import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AlertTriangle } from 'lucide-react';
export const GlobalSessionAlert = ({ isOpen, onClose }) => {
    if (!isOpen)
        return null;
    const handleConfirm = () => {
        onClose();
        // Redirigir al login
        window.location.href = '/login';
    };
    return (_jsxs("div", { className: "fixed inset-0 z-[9999] flex items-center justify-center", children: [_jsx("div", { className: "absolute inset-0 bg-black/70 backdrop-blur-sm animate-in fade-in duration-200" }), _jsxs("div", { className: "relative bg-white rounded-2xl shadow-2xl max-w-lg w-full mx-4 overflow-hidden animate-in fade-in-0 zoom-in-95 duration-300", children: [_jsx("div", { className: "bg-gradient-to-r from-orange-500 to-red-600 px-6 py-5", children: _jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("div", { className: "bg-white/20 p-3 rounded-full animate-pulse", children: _jsx(AlertTriangle, { className: "h-8 w-8 text-white", strokeWidth: 2.5 }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-xl font-bold text-white", children: "Sesi\u00F3n Cerrada" }), _jsx("p", { className: "text-white/90 text-sm mt-1", children: "Por el administrador del sistema" })] })] }) }), _jsx("div", { className: "px-6 py-6", children: _jsxs("div", { className: "space-y-4", children: [_jsxs("p", { className: "text-gray-700 text-base leading-relaxed", children: ["Tu sesi\u00F3n ha sido ", _jsx("strong", { className: "text-red-600", children: "cerrada por un administrador" }), ". Esto puede deberse a razones de seguridad o mantenimiento del sistema."] }), _jsx("div", { className: "bg-blue-50 border-l-4 border-blue-500 p-4 rounded-r-lg", children: _jsxs("div", { className: "flex items-start", children: [_jsx("div", { className: "flex-shrink-0", children: _jsx("svg", { className: "h-5 w-5 text-blue-500 mt-0.5", fill: "currentColor", viewBox: "0 0 20 20", children: _jsx("path", { fillRule: "evenodd", d: "M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z", clipRule: "evenodd" }) }) }), _jsxs("div", { className: "ml-3", children: [_jsx("p", { className: "text-sm text-blue-800 font-medium", children: "\u00BFQu\u00E9 hacer ahora?" }), _jsx("p", { className: "text-sm text-blue-700 mt-1", children: "Deber\u00E1s iniciar sesi\u00F3n nuevamente para continuar usando el sistema." })] })] }) })] }) }), _jsx("div", { className: "px-6 py-4 bg-gray-50 flex justify-end border-t border-gray-200", children: _jsx("button", { onClick: handleConfirm, className: "px-6 py-2.5 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white rounded-lg font-semibold transition-all duration-200 shadow-lg hover:shadow-xl transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2", children: "Ir al Login" }) })] })] }));
};
